### ISSUE TITLE
Stuck in Loading Build...

### ISSUE THREAD

**Issue by paulirish** [juliangruber/travis-watch#35]
I was just trying out travis-watch in my project's master branch and it appeared to get "stuck" in loading build. (I hadn't pushed recently, but was curious what happened regardless)

Poked into the code and it looks like it's just in the `getBuild` callback repeatedly. 
Perhaps I'm holding it wrong :)

Excited to use this.. thanks!

**Comment by juliangruber** [comment]
What's happening is most likely since you didn't push recently it kept waiting for your current latest git commit to appear in a travis build.

I see two parts to the solution:

1) We could add some cli options to for example display the most recent build in the current branch
2) We should display a warning when fetching the build takes too long

Thanks for submitting this!

**Comment by juliangruber** [comment]
This is the default behavior as it makes it easy to integrate into your tooling, so you can have scripts like this: https://github.com/juliangruber/npm-publish/blob/add/travis-watch/publish.sh

**Comment by s3ththompson** [comment]
This is a fun one. I ran into the same thing as @paulirish and I think the bug is actually a bit more subtle.

`travis-watch`, the `travis-ci` Node client, and the Travis CI API itself only accept canonical usernames and repo names, not lowercased ones.

<img width="842" alt="screen shot 2017-03-28 at 2 49 22 pm" src="https://cloud.githubusercontent.com/assets/970121/24405600/c0b53088-13c5-11e7-8cdc-24a51c183a5f.png">


My git config had the remote origin as `git@github.com:webassembly/website`. Changing it to `git@github.com:WebAssembly/website` started working.

Perhaps you could add a step to fetch the canonical repo name with the GitHub API if the Travis CI API doesn't turn up anything.

**Comment by juliangruber** [comment]
Ah, yeah I've seen that before with another repo, but was hoping that was an odd case. I'll add that additional step :)

**Comment by juliangruber** [comment]
This is fixed now in 1.16.0, once the local git config has been parsed it will also hit the public github repos api to resolve and override the locally parsed repo info.

Does this solve it for you?

**Comment by s3ththompson** [comment]
@juliangruber works for me, thanks!
